name = "komali-sarees"
compatibility_date = "2024-01-01"
# The directory where Vite outputs the build
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "komali_db"
database_id = "3de0e03f-9d94-4b33-9132-0364f9345563"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "komali-assets"
